### ISSUE TITLE
baidu password is not working

### ISSUE THREAD

**Issue by DrBlou** [NNNNAI/VGGFace2-HQ#1]
Hi, i wanted to try but the baidu password : jd2v isn't working, can you do something about it ?

Thanks in advance

**Comment by NNNNAI** [comment]
Hi, the correct password is "sjtu", I have been updated it in Readme. Sorry for the inconvenience caused by the wrong password. Have a nice day.

**Comment by DrBlou** [comment]
Hi thanks for the fast answer, i didn't noticed .. have a nice day
