### ISSUE TITLE
the zip file in baidu is broken?

### ISSUE THREAD

**Issue by threefoldo** [NNNNAI/VGGFace2-HQ#12]
Hi,
  I cannot unzip the zip files in Ubuntu 20.04, the file size seems OK, but got a lot of errors (only one image file is correctly extracted):
```
unzip VGGface2_HQ.zip
file #117124:  bad zipfile offset (local header sig):  9635728212

file VGGface2_HQ.zip
VGGface2_HQ.zip: DOS executable (COM, 0x8C-variant)

$ md5sum VGG*
b0b85056138ec65b545e8d43c17a1a4f  VGGface2_HQ.z01
9d0f8f07f5cda2ac7c32248ba54d220a  VGGface2_HQ.z02
f98596d310007c87fe45d2b1371aae24  VGGface2_HQ.z03
f025c8d036c027eb4ee5af173965d85f  VGGface2_HQ.z04
e5693cb420a648eb4630b4740f427c42  VGGface2_HQ.zip

```

**Comment by threefoldo** [comment]
Those files are fine, I encountered a download problem somewhere.

**Comment by ygtxr1997** [comment]
Could you provide the md5 values of your downloaded files?

**Comment by QinjieXiao** [comment]
> Those files are fine, I encountered a download problem somewhere.

Hi, could you provide the right md5 values?
