### ISSUE TITLE
How to cite this project?

### ISSUE THREAD

**Issue by YoucanBaby** [NNNNAI/VGGFace2-HQ#19]
Dear developer,

Thanks for your great project.
How to cite this project?

Best regards.

**Comment by neuralchen** [comment]
Thank you for your interest in our project!
You can cite our TPAMI paper:
@article{simswapplusplus,
  author       = {Xuanhong Chen and
                  Bingbing Ni and
                  Yutian Liu and
                  Naiyuan Liu and
                  Zhilin Zeng and
                  Hang Wang},
  title        = {SimSwap++: Towards Faster and High-Quality Identity Swapping},
  journal      = {{IEEE} Trans. Pattern Anal. Mach. Intell.},
  volume       = {46},
  number       = {1},
  pages        = {576--592},
  year         = {2024}
}
