### ISSUE TITLE
Could not load library cudnn_ops_infer64_8.dll

### ISSUE THREAD

**Issue by bmc84** [NNNNAI/VGGFace2-HQ#2]
Hi,

Command: 
**python scripts/crop_align_vggface2_FFHQalign.py --input_dir /in --output_dir_ffhqalign /out --mode ffhq --crop_size 256**

Gives error:
_Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!_

cudnn_ops_infer64_8.dll is definitely there. I cloned my SimSwap environment, then "pip install"ed the extra requirements.

Any idea why this does not work?

**Comment by NNNNAI** [comment]
Did you install the onnxruntime-gpu? The problem may be caused by the failure to install onnxruntime-gpu. Try pip uninstall onnxruntime-gpu first, and then run the command again to check whether the operation succeeds.

**Comment by bmc84** [comment]
Ok thanks it seems to work now.

It finds 3 images in my IN folder. but then in the OUT folder, it creates 3 folders with the names of the input files, but nothing is in them?

![image](https://user-images.githubusercontent.com/87626308/142582637-0e2057c5-f448-44d1-8662-9e68cddcc5db.png)

**Comment by NNNNAI** [comment]
Becasuse crop_align_vggface2_FFHQalign.py is designed for VGGface2. What this code expects is that the folder you copy to --input_dir should have many subfolders, each with many pictures. The code will process all the images in the subfolders. But you don't have any subfolders in your case. You can do this by creating a new folder in IN folder, putting all three images in the new folder, and then leaving the command line unchanged.

**Comment by bmc84** [comment]
Ok.

I now have IN\SUB_FOLDER and IN\SUB_FOLDER_2 each with 3 images:
![image](https://user-images.githubusercontent.com/87626308/142584969-39875a13-920e-41aa-8a20-4103cb6b3a0f.png)

I then run command:
python scripts/crop_align_vggface2_FFHQalign.py --input_dir in --output_dir_ffhqalign out --mode ffhq --crop_size 256

![image](https://user-images.githubusercontent.com/87626308/142585081-882f55f7-7541-42ed-94e0-d0c8d7e96093.png)

but in OUT folder, there are no files
![image](https://user-images.githubusercontent.com/87626308/142585137-bdd98555-1764-4190-bb11-34459ecdf502.png)

Why would this be?
The faces are definitely "detectable" - they were found & generated by SimSwap.

**Comment by NNNNAI** [comment]
Is the the height and width of images in IN subfolder  both bigger than 250?

**Comment by NNNNAI** [comment]
Insert "print(image_file)" at the line 30 of  crop_align_vggface2_FFHQalign.py, and let me see the log in the terminal.

**Comment by NNNNAI** [comment]
I found the problem, try this new crop_align_vggface2_FFHQalign.py. And it should work now.
[crop_align_vggface2_FFHQalign.zip](https://github.com/NNNNAI/VGGFace2-HQ/files/7568757/crop_align_vggface2_FFHQalign.zip)

**Comment by bmc84** [comment]
It works now! Thank you so much.
