### ISSUE TITLE
How do we uncompress the files to see the data?

### ISSUE THREAD

**Issue by jhkonan** [NNNNAI/VGGFace2-HQ#7]
This looks like an interesting dateset, but I am not sure how to open these files given their non-standard naming convention. I'm also not sure why one of them is a zip, while the others are not.

On Linux, could you go through the commands needed to open the files and organize them into the same file structure as the original VGGFace2?

```
/VGGFace2-HQ/VGGface2_HQ.zip
/VGGFace2-HQ/VGGface2_HQ.z01
/VGGFace2-HQ/VGGface2_HQ.z02
/VGGFace2-HQ/VGGface2_HQ.z03
/VGGFace2-HQ/VGGface2_HQ.z04
```

Thank you for your help.

**Comment by Prashant-Kesharwani** [comment]
Move all files into a Single Directory!

Install 7-Zip (if not already installed):

`sudo apt-get install p7zip-full`

Extract the split archive using 7-Zip:


`7z x VGGface2_HQ.zip`

7-Zip should automatically detect and handle the split files (.z01, .z02, etc.) and extract them correctly. If this still doesn't work, it may indicate that there is an issue with one or more of the split files. Make sure that all parts of the archive are present and have not been corrupted during the download.
